version: '3.3'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'flower-ride-database'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '15000:3306'
    expose:
      # Opens port 3307 on the container
      - '15000'
      # Where our data will be persisted
    volumes:
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
